In [27]:
# Python program to add two Matrices
A=[[1,3,5],[6,8,9],[1,1,1]]

B=[[2,4,5],[2,4,1],[1,1,1]]
print(len(A[0]))
len(A)

result=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j]=A[i][j]+B[i][j]
        
for r in result:
    print(r)


3
[3, 7, 10]
[8, 12, 10]
[2, 2, 2]


In [32]:
# Python program to multiply two matrices
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]

result = [[0,0,0], 
          [0,0,0], 
          [0,0,0]]

for i in range(len(X)): 
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j] 
            
for r in result: 
    print(r)

X[1][1]

[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


5

In [33]:
# Python program for Matrix Product
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]

result = [[0,0,0], 
          [0,0,0], 
          [0,0,0]]

for i in range(len(X)): 
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j] 
            
for r in result: 
    print(r)

X[1][1]

[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


5

In [41]:
# Adding and Subtracting Matrices in Python
import numpy as np
A=[[1,2,3],[1,2,3],[1,2,3]]
B=[[1,2,3],[1,2,3],[1,2,3]]
print(A)
print(B)
print(np.add(A,B))
print(np.subtract(A,B))

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [42]:
# Transpose a matrix in Single line in Python
import numpy as np
matrix = [[1,2,3],
          [4,5,6]]
print(matrix)
print("\n")
print(np.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [69]:
# Python | Matrix creation of n*n
N =4 
print("The Dimension:" +str(N))
res = [list(range(1 + N * i,1+ N * (i + 1)))
       for i in range(N)]

print("The created matrix of N * N: " + str(res))

The Dimension:4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [68]:
# Python | Get Kth Column of Matrix
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
print("The original list is : " + str(test_list)) 
K = 2

res = [sub[K] for sub in test_list] 

print("The Kth column of Matrix is :" + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of Matrix is :[6, 10, 5]


In [67]:
# Python – Vertical Concatenation in Matrix
test_list = [["abc", "good"], ["efg", "for"], ["hij"]]
print("The original list : " + str(test_list)) 


res = [] 
N = 0 

while N != len(test_list): 
    temp = '' 
    for idx in test_list:
        try: temp = temp + idx[N] 
        except IndexError: pass 
    res.append(temp) 
    N = N + 1 

res = [ele for ele in res if ele] 

print("List after column Concatenation : " + str(res)) 

The original list : [['abc', 'good'], ['efg', 'for'], ['hij']]
List after column Concatenation : ['abcefghij', 'goodfor']


In [57]:
# Python program to check if a string is palindrome or not
def ispalindrome(s):
    return s==s[::-1]

s='rakesh'
a=ispalindrome(s)
if a:
    print('Yes')
else:
    print('No')

No


In [65]:
# Python program to check whether the string is Symmetrical or Palindrome
string = 'rakesh' 
half = int(len(string) / 2) 
if len(string) % 2 == 0:
    first_str = string[:half]
    second_str = string[half:]
else:
    first_str= string[:half]
    second_str= string[half+1:]

#symetric
if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')
if first_str == second_str[::-1]:
    print(string, 'string is palindrome') 
else: 
    print(string, 'string is not palindrome') 

rakesh string is not symmertical
rakesh string is not palindrome
